spring:
  datasource:
    # ez az URL kell akkor, ha csak az adatbázis fut konténerben, az alkalmazást meg IDEA-ból vagy külön indítjátok el
    url: jdbc:mysql://127.0.0.1:3307/conference?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    # ez az URL kell akkor, ha az adatbázist és az alkalmazást is konténerizálva futtatjátok
  #  url: jdbc:mysql://conferencedb/conference?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: on
logging:
  level:
    org:
      flywaydb: debug

